#!/bin/bash
[ ! -d /tmp/$USER ] && mkdir /tmp/$USER
pwd > /tmp/$USER/CD_SAVED

if [ -z $VIRTUAL_ENV ]
    then
        #echo "VE is not set"
        [ -f /tmp/$USER/ENV_SAVED ] && rm /tmp/$USER/ENV_SAVED
    else
        #VE is  set
        _env=$(basename $VIRTUAL_ENV)
        echo $_env > /tmp/$USER/ENV_SAVED
fi
