#!/bin/bash
docker run --rm -it \
	--net host \
	--cpuset-cpus 0 \
	--memory 512mb \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-e DISPLAY=unix$DISPLAY \
	--security-opt seccomp=$HOME/.dockerfiles/chrome/chrome.json \
	--device /dev/snd \
	-v /dev/shm:/dev/shm \
	--name chrome \
	ali7line/chrome
